# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca0268e9abfcbaf4f0582abdc66e05828f88fab6d78037aecbdc301b765721bbb3db94b59eca615a946d6220896f6f47f670a35287dc7d2d4db595c9097bc142

test:
  secret_key_base: 4e3233539338d802b49da0e75f3d181f0fda1024b01f9f70b2af04154887654fb635ed6e1b205cc74e67b37222e5d7881e6ade1824e02be165033d7655d83ddd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
